metricPrefix: "Custom Metrics|Log Monitor|"

logs:
- displayName: "Machine Agent Logs"
  logDirectory: "/opt/appdynamics/machine-agent/logs"
  logName: "machine-agent.log"
  searchStrings:
  - displayName: "Log Monitor Task"
    pattern: "LogMonitorTask"
    matchExactString: false
    caseSensitive: true
    printMatchedString: true


#Replaces characters in metric name with the specified characters.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters
metricCharacterReplacer:
- replace: ":"
  replaceWith: ";"
- replace: "\\|"
  replaceWith: "#"

# Number of concurrent threads
numberOfThreads: 20

#Thread timeout in seconds
threadTimeOut: 60

sendDataToEventsService: true

logMatchOffset: 2

# This field contains the various parameters required to initiate a connection and send data to the AppDynamics Events Service.
eventsServiceParameters:
  host: "controller"
  port: 9080
  globalAccountName:
  eventsApiKey: "4a5c3998-8914-4a57-a2f2-920cd76c08ae"
  useSSL: false

# Generate a custom dashboard based on the provided template
customDashboard:
  enabled: true
  dashboardName: "Log Monitor Dashboard"
  #  sslCertCheckEnabled: true
  # Update the path to the dashboard file.
  pathToSIMDashboard: "monitors/LogMonitor/SIMDashboard.json"
  pathToNormalDashboard:
  periodicDashboardCheckInSeconds: 60

# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile. Please refer to ControllerInfoFactory for more details.
controllerInfo:
  controllerHost: "controller"
  controllerPort: 8080
  account: "customer1"
  username: "user1"
  password: "welcome"
  encryptedPassword: ""
  encryptionKey: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: "${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}"
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""

enableHealthChecks: true # If not set, will be retrieved from "-Dappdynamics.agent.monitors.healthchecks.enable=true". Defaults to true.